version: "3.9"
services:
  job4j_db:
    build:
      context: .
    container_name:   job4j_db
  job4j_docker:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - API=job4j_db
    container_name: job4j_docker
    depends_on:
      - job4j_db